spring.application.name=formativa2

# Se configura el puerto del servidor para que sea 8080 de forma manual 
# se puede cambiar rápidamente si es necesario para evitar conflictos con otros microservicios que puedan 
# estar corriendo en el mismo host (Usuarios puerto 8080).
server.port=8080



# Forzar codificación UTF-8 global para peticiones y respuestas JSON
# Para evitar problemas de codificación de caracteres en los microservicios, 
# se establece la codificación UTF-8 para todas las solicitudes y respuestas JSON.

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true