CREATE TABLE pelicula (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo   VARCHAR2(150) NOT NULL,
    anio     NUMBER(4) NOT NULL,
    director VARCHAR2(150) NOT NULL,
    genero   VARCHAR2(100) NOT NULL,
    sinopsis VARCHAR2(1000) NOT NULL
);

INSERT INTO pelicula (id, titulo, anio, director, genero, sinopsis)
VALUES (1, 'Crepúsculo', 2008, 'Catherine Hardwicke', 'Romance / Fantasía',
        'Bella se muda a un pueblo y se enamora de un vampiro.');

INSERT INTO pelicula (id, titulo, anio, director, genero, sinopsis)
VALUES (2, 'Hotel Budapest', 2014, 'Wes Anderson', 'Comedia / Drama',
        'Aventuras de un conserje de hotel en la Europa de entreguerras.');

INSERT INTO pelicula (id, titulo, anio, director, genero, sinopsis)
VALUES (3, 'Terminator', 1984, 'James Cameron', 'Ciencia Ficción / Acción',
        'Un ciborg llega del futuro para matar a la madre del líder rebelde.');

INSERT INTO pelicula (id, titulo, anio, director, genero, sinopsis)
VALUES (4, 'Inception', 2010, 'Christopher Nolan', 'Ciencia Ficción / Acción',
        'Un experto en robar secretos mediante sueños recibe una misión inversa.');

INSERT INTO pelicula (id, titulo, anio, director, genero, sinopsis)
VALUES (5, 'Misión Imposible', 1996, 'Brian De Palma', 'Suspenso / Espionaje',
        'Un agente es culpado de la muerte de su equipo y busca al verdadero traidor.');

INSERT INTO pelicula (id, titulo, anio, director, genero, sinopsis)
VALUES (6, 'Los Juegos del Hambre', 2012, 'Gary Ross', 'Ciencia Ficción / Acción',
        'En un futuro post-apocalíptico, jóvenes son forzados a participar en un combate mortal televisado.');

INSERT INTO pelicula (id, titulo, anio, director, genero, sinopsis)
VALUES (7, 'El Exorcista', 1973, 'William Friedkin', 'Terror',
        'Una niña es poseída por una entidad demoníaca y dos sacerdotes intentan salvarla.');

INSERT INTO pelicula (id, titulo, anio, director, genero, sinopsis)
VALUES (8, 'Constantine', 2005, 'Francis Lawrence', 'Fantasía / Acción',
        'Un detective especializado en lo sobrenatural investiga fuerzas demoníacas y angelicales.');

INSERT INTO pelicula (id, titulo, anio, director, genero, sinopsis)
VALUES (9, 'La Gran Estafa', 2001, 'Steven Soderbergh', 'Crimen / Suspenso',
        'Danny Ocean planea el robo más ambicioso de la historia a tres casinos de Las Vegas.');

INSERT INTO pelicula (id, titulo, anio, director, genero, sinopsis)
VALUES (10, 'Hombres de Negro', 1997, 'Barry Sonnenfeld', 'Ciencia Ficción / Comedia',
        'Una organización secreta vigila la actividad extraterrestre en la Tierra.');

COMMIT;